/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.Set;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Nico
 */
public class FormRuta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRuta.class.getName());

    /**
     * Creates new form FormRutas
     */
    public FormRuta() {
        initComponents();
    }
    public FormRuta(InterfazControlador _app){
        initComponents();
        app = _app;
        cargarOpciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bConfirmarForm = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        bCancelarForm = new javax.swing.JButton();
        selectorOrigen = new javax.swing.JComboBox<>();
        selectorDestino = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario de Ruta");
        setMinimumSize(new java.awt.Dimension(400, 400));

        bConfirmarForm.setText("Confirmar");
        bConfirmarForm.addActionListener(this::bConfirmarFormActionPerformed);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de Ruta");

        jLabel2.setText("Origen");
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 50));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 20));
        jLabel2.setRequestFocusEnabled(false);

        jLabel3.setText("Destino");
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 20));
        jLabel3.setRequestFocusEnabled(false);

        bCancelarForm.setText("Cancelar");
        bCancelarForm.addActionListener(this::bCancelarFormActionPerformed);

        selectorOrigen.setMinimumSize(new java.awt.Dimension(150, 20));
        selectorOrigen.setPreferredSize(new java.awt.Dimension(200, 20));

        selectorDestino.setMinimumSize(new java.awt.Dimension(150, 20));
        selectorDestino.setPreferredSize(new java.awt.Dimension(200, 20));
        selectorDestino.addActionListener(this::selectorDestinoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectorOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selectorDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(bCancelarForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bConfirmarForm)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectorDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bConfirmarForm)
                    .addComponent(bCancelarForm))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void cargarOpciones(){
        Set<Entidad> vectores =  app.getGrafo().vertexSet();
        Vector<String> opciones = new Vector<>();
        for(Entidad e : vectores){
            opciones.add(e.getNombre());
        }

        selectorDestino.setModel(new DefaultComboBoxModel<>(opciones));
        selectorOrigen.setModel(new DefaultComboBoxModel<>(opciones));


    }

    private void bConfirmarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarFormActionPerformed
        //cuando se presiona confirmar
        String origen = selectorOrigen.getSelectedItem().toString();
        String destino = selectorDestino.getSelectedItem().toString();

        if(origen.equals(destino)){
            JOptionPane.showMessageDialog(this, "La ruta debe tener un origen y destino distintos");
            return;
        }

        app.agregarRuta(origen, destino);
        setVisible(false);

    }//GEN-LAST:event_bConfirmarFormActionPerformed

    private void bCancelarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarFormActionPerformed
        setVisible(false);
    }//GEN-LAST:event_bCancelarFormActionPerformed

    private void selectorDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectorDestinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormRuta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelarForm;
    private javax.swing.JButton bConfirmarForm;
    private javax.swing.JComboBox<String> selectorDestino;
    private javax.swing.JComboBox<String> selectorOrigen;
    // End of variables declaration//GEN-END:variables
    private InterfazControlador app;
}
