/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nico
 */
public class UIEnviosRuta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UIEnviosEntidad.class.getName());

    /**
     * Creates new form UIInventario
     */
    public UIEnviosRuta() {
        initComponents();
    }

    public UIEnviosRuta( InterfazControlador _app,String _origen, String _destino){
        initComponents();
        app = _app;
        origen = _origen;
        destino = _destino;
        actualizar();
    }

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEnvios = new javax.swing.JTable();
        bCancelar = new javax.swing.JButton();
        bLiberar = new javax.swing.JButton();

        setTitle("Vizualizar Envios");
        setMinimumSize(new java.awt.Dimension(300, 600));

        tablaEnvios.setAutoCreateRowSorter(true);
        tablaEnvios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Origen", "Destino", "Contenido", "ETA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEnvios);

        bCancelar.setText("Cancelar Envio");
        bCancelar.setMaximumSize(new java.awt.Dimension(200, 30));
        bCancelar.setMinimumSize(new java.awt.Dimension(100, 20));
        bCancelar.setPreferredSize(new java.awt.Dimension(150, 20));
        bCancelar.addActionListener(this::bCancelarActionPerformed);

        bLiberar.setText("Marcar Entregado");
        bLiberar.setMaximumSize(new java.awt.Dimension(200, 30));
        bLiberar.setMinimumSize(new java.awt.Dimension(100, 20));
        bLiberar.setPreferredSize(new java.awt.Dimension(150, 20));
        bLiberar.addActionListener(this::bLiberarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLiberar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(bLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        int fila = tablaEnvios.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(this, "Selecciona un envio de la tabla");
            return;
        }
        int ID =(int)tablaEnvios.getValueAt(fila, 0);
        app.cancelarEnvio(ID);
        actualizar();

    }//GEN-LAST:event_bCancelarActionPerformed

    private void bLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLiberarActionPerformed
        int fila = tablaEnvios.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(this, "Selecciona un envio de la tabla");
            return;
        }
        int ID =(int)tablaEnvios.getValueAt(fila, 0);
        app.avanzarEnvio(ID);
        actualizar();
    }//GEN-LAST:event_bLiberarActionPerformed


    public void actualizar(){
        tablaEnvios.setModel(app.getTablaEnviosRuta((DefaultTableModel)tablaEnvios.getModel(), origen,destino));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UIEnviosEntidad().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bLiberar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEnvios;
    // End of variables declaration//GEN-END:variables
    private String origen;
    private String destino;
    private InterfazControlador app;
}
