/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nico
 */
public class UIInventario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UIInventario.class.getName());

    /**
     * Creates new form UIInventario
     */
    public UIInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        labelEntidad = new javax.swing.JLabel();
        bAgregarInventario = new javax.swing.JButton();
        bModificarInventario = new javax.swing.JButton();
        bEliminarInventario = new javax.swing.JButton();
        bRealizarEnvio = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(300, 600));
        setPreferredSize(new java.awt.Dimension(500, 800));

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Contenido", "Cantidad ", "Peso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaInventario);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inventario");

        labelEntidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEntidad.setText("<entidad>");

        bAgregarInventario.setText("Agregar al inventario");
        bAgregarInventario.setMaximumSize(new java.awt.Dimension(200, 30));
        bAgregarInventario.setMinimumSize(new java.awt.Dimension(100, 20));
        bAgregarInventario.setPreferredSize(new java.awt.Dimension(150, 20));
        bAgregarInventario.addActionListener(this::bAgregarInventarioActionPerformed);

        bModificarInventario.setText("Modificar paquete");
        bModificarInventario.setMaximumSize(new java.awt.Dimension(200, 30));
        bModificarInventario.setMinimumSize(new java.awt.Dimension(100, 20));
        bModificarInventario.setPreferredSize(new java.awt.Dimension(150, 20));
        bModificarInventario.addActionListener(this::bModificarInventarioActionPerformed);

        bEliminarInventario.setText("Eliminar paquete");
        bEliminarInventario.setMaximumSize(new java.awt.Dimension(200, 30));
        bEliminarInventario.setMinimumSize(new java.awt.Dimension(100, 20));
        bEliminarInventario.setPreferredSize(new java.awt.Dimension(150, 20));
        bEliminarInventario.addActionListener(this::bEliminarInventarioActionPerformed);

        bRealizarEnvio.setText("Realizar Envio");
        bRealizarEnvio.setMaximumSize(new java.awt.Dimension(200, 30));
        bRealizarEnvio.setMinimumSize(new java.awt.Dimension(100, 20));
        bRealizarEnvio.setPreferredSize(new java.awt.Dimension(150, 20));
        bRealizarEnvio.addActionListener(this::bRealizarEnvioActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bAgregarInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bModificarInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bEliminarInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bRealizarEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelEntidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(labelEntidad)
                        .addGap(99, 99, 99)
                        .addComponent(bAgregarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bModificarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bRealizarEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bEliminarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bModificarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bModificarInventarioActionPerformed

    private void bAgregarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAgregarInventarioActionPerformed

    private void bEliminarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bEliminarInventarioActionPerformed

    private void bRealizarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizarEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bRealizarEnvioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UIInventario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarInventario;
    private javax.swing.JButton bEliminarInventario;
    private javax.swing.JButton bModificarInventario;
    private javax.swing.JButton bRealizarEnvio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEntidad;
    private javax.swing.JTable tablaInventario;
    // End of variables declaration//GEN-END:variables
}
