import org.jgrapht.Graph;
import org.jgrapht.ext.*;
import org.jgrapht.graph.DefaultWeightedEdge;

import com.mxgraph.model.mxGeometry;
import com.mxgraph.model.mxICell;
import com.mxgraph.swing.mxGraphComponent;
import com.mxgraph.util.mxConstants;
import java.util.Map;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nico
 */
public class UiVentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UiVentanaPrincipal.class.getName());

    /**
     * Creates new form UiVentanaPrincipal
     */
    public UiVentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelVistaGeneral = new javax.swing.JPanel();
        PanelEntidades = new javax.swing.JPanel();
        bAgregarEntidad = new javax.swing.JButton();
        bEliminarEntidad = new javax.swing.JButton();
        bActualizarContacto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEntidades = new javax.swing.JTable();
        javax.swing.JPanel PanelRutas = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador de Red de Suministros");
        setLocation(new java.awt.Point(80, 80));
        setName("ventana"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(800, 600));
        jTabbedPane1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout PanelVistaGeneralLayout = new javax.swing.GroupLayout(PanelVistaGeneral);
        PanelVistaGeneral.setLayout(PanelVistaGeneralLayout);
        PanelVistaGeneralLayout.setHorizontalGroup(
            PanelVistaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );
        PanelVistaGeneralLayout.setVerticalGroup(
            PanelVistaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Vista general", PanelVistaGeneral);

        bAgregarEntidad.setText("Agregar Entidad");
        bAgregarEntidad.setMinimumSize(new java.awt.Dimension(150, 20));
        bAgregarEntidad.addActionListener(this::bAgregarEntidadActionPerformed);

        bEliminarEntidad.setText("Eliminar Entidad");
        bEliminarEntidad.setMinimumSize(new java.awt.Dimension(150, 20));
        bEliminarEntidad.addActionListener(this::bEliminarEntidadActionPerformed);

        bActualizarContacto.setText("Actualizar Contacto");
        bActualizarContacto.setMinimumSize(new java.awt.Dimension(150, 20));
        bActualizarContacto.addActionListener(this::bActualizarContactoActionPerformed);

        TablaEntidades.setAutoCreateRowSorter(true);
        TablaEntidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Rol", "Contacto", "Ubicacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaEntidades.setColumnSelectionAllowed(true);
        TablaEntidades.setMaximumSize(new java.awt.Dimension(2147483647, 600));
        TablaEntidades.setMinimumSize(new java.awt.Dimension(500, 80));
        TablaEntidades.setPreferredSize(new java.awt.Dimension(500, 400));
        jScrollPane1.setViewportView(TablaEntidades);

        javax.swing.GroupLayout PanelEntidadesLayout = new javax.swing.GroupLayout(PanelEntidades);
        PanelEntidades.setLayout(PanelEntidadesLayout);
        PanelEntidadesLayout.setHorizontalGroup(
            PanelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntidadesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAgregarEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bEliminarEntidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bActualizarContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelEntidadesLayout.setVerticalGroup(
            PanelEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntidadesLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(bAgregarEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(bEliminarEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(bActualizarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelEntidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Entidades", PanelEntidades);

        jButton4.setText("Agregar Ruta");
        jButton4.setMaximumSize(new java.awt.Dimension(160, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(150, 20));
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Modificar Ruta");
        jButton5.setMaximumSize(new java.awt.Dimension(160, 30));
        jButton5.setMinimumSize(new java.awt.Dimension(150, 20));
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Eliminar Ruta");
        jButton6.setMaximumSize(new java.awt.Dimension(160, 30));
        jButton6.setMinimumSize(new java.awt.Dimension(150, 20));
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Origen", "Destino", "Distancia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout PanelRutasLayout = new javax.swing.GroupLayout(PanelRutas);
        PanelRutas.setLayout(PanelRutasLayout);
        PanelRutasLayout.setHorizontalGroup(
            PanelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRutasLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(PanelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelRutasLayout.setVerticalGroup(
            PanelRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRutasLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelRutasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rutas", PanelRutas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarEntidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAgregarEntidadActionPerformed

    private void bEliminarEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarEntidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bEliminarEntidadActionPerformed

    private void bActualizarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActualizarContactoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UiVentanaPrincipal().setVisible(true));
    }

    public void setGrafo(Graph<Entidad,Ruta> grafoOriginal){
        //Limpia el panel del grafo anterior
        PanelVistaGeneral.removeAll();
        PanelVistaGeneral.setLayout(new java.awt.BorderLayout());

        //crea un adaptador usando el grafo 
        JGraphXAdapter<Entidad, Ruta> adapter = new JGraphXAdapter<>(grafoOriginal);

        //crea un elemento visual usando el adaptador
        grafoVisual = new mxGraphComponent(adapter);
        grafoVisual.setPreferredSize(new java.awt.Dimension(600, 400));

        //asigna posiciones a los nodos segun su ubicacion
        for (Map.Entry<Entidad, mxICell> entry : adapter.getVertexToCellMap().entrySet()) {
            Entidad entidad = entry.getKey();
            Object cell = entry.getValue();
            int[] ubicacion = entidad.getUbicacion();

            int x = ubicacion[0] * 50 + 250;
            int y = ubicacion[1] * 50 + 150;

            mxGeometry geometry = new mxGeometry(x, y, 90, 30);
            geometry.setRelative(false);
            adapter.getModel().setGeometry(cell, geometry);
        }

        adapter.getStylesheet().getDefaultEdgeStyle().put(mxConstants.STYLE_NOLABEL, "false");
        adapter.getStylesheet().getDefaultEdgeStyle().put(mxConstants.STYLE_EDGE, "orthogonalEdgeStyle");
        adapter.getStylesheet().getDefaultEdgeStyle().put(mxConstants.STYLE_ROUNDED, "true");

        grafoVisual.getGraph().setCellsEditable(false);
        grafoVisual.getGraph().setCellsResizable(false);
        grafoVisual.getGraph().setCellsMovable(false);
        grafoVisual.getGraph().setVertexLabelsMovable(false);
        grafoVisual.getGraph().setCellsLocked(true);


        
        PanelVistaGeneral.add(grafoVisual, java.awt.BorderLayout.CENTER);
        PanelVistaGeneral.revalidate();
        PanelVistaGeneral.repaint();
        PanelVistaGeneral.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEntidades;
    private javax.swing.JPanel PanelVistaGeneral;
    private javax.swing.JTable TablaEntidades;
    private javax.swing.JButton bActualizarContacto;
    private javax.swing.JButton bAgregarEntidad;
    private javax.swing.JButton bEliminarEntidad;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
    private mxGraphComponent grafoVisual;
}
